### ISSUE TITLE
After system update, main section of DM page isn't themed

### ISSUE THREAD

**Issue by GideonWolfe** [guglicap/wal-discord#33]
Hello, me again. This tool has been flawless since my last issue. Now I updated my system (discord probably updated too) and the main section of the DM page is default grey.

![image](https://user-images.githubusercontent.com/32942052/148863343-c4965ea4-9ec3-4c38-8820-87fe8c6d8aba.png)

Whereas the servers themselves seem to load fine

![image](https://user-images.githubusercontent.com/32942052/148863466-5b459c2e-bf0c-4ea8-a062-593f48c58439.png)

Maybe this is just a single CSS classname that got changed or something?

**Comment by GideonWolfe** [comment]
fixed the main background color issue as well as the red notification bubbles by adding

```css
// fixes background of online friends list on DMs page
.theme-dark .container-2cd8Mz {
    background-color: $bg !important;
}

// Background color of server notification bubbles
.numberBadge-37OJ3S, .base-3IDx3, .baseShapeRound-3epLEv {
    background-color: $colorUrgent !important;
}
```

Not sure about the other items tho :/
